# Problem 1 

In [5]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
x = np.random.randint(0,10,size=(5))
print(x)
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
x.sort()
print(x)

[8 7 6 6 5]
[5 6 6 7 8]


# Problem 2

In [37]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a = np.array

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
x = np.random.randint(0,10,size=(2,5))# bir aralıktan rastgele sayılar üretir.
print(x)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
a = np.arange(50,101,5)
print(a)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
v = np.zeros(10)
print(v)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
l = np.ones(10)
print(l)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
x = np.linspace(0,101,25)
print(x)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
x = np.random.randint(10,31,5)
print(x)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
x = np.random.randint(-1,2,size=(10)).astype(float)# bir aralıktan rastgele sayılar üretir.
print(x) 

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
x = np.random.randint(9,50,size=(2,5))# bir aralıktan rastgele sayılar üretir.
print(x)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?

print(x.shape[0] + x.shape[1]) # satır sayısı + sütun sayısı


# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(x.max()) # en büyük eleman
print(x.min()) # en küçük eleman
print(x.mean()) # ortalama

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(x.argmax()) # en büyük elemanın indeksi

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
x[0:3] # 0'dan 3'e kadar olan elemanları alır. 0 dahil, 3 hariç.
print(x[0:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(x[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(x[0]) # 0. satır

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(x[1,2]) # 1. satır 2. sütundaki eleman

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(x[:,0]) # tüm satırlardaki 0. sütundaki elemanları alır.

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(x**2) # her bir elemanın karesini alır.

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
x = np.random.randint(-50,50,size=(2,5))# bir aralıktan rastgele sayılar üretir.
print(x) # rastgele üretilen matris
print(x[(x > 0) & (x % 2 == 0)]) # pozitif çift sayıları alır.



[[8 6 2 3 0]
 [5 3 4 7 3]]
[ 50  55  60  65  70  75  80  85  90  95 100]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.           4.20833333   8.41666667  12.625       16.83333333
  21.04166667  25.25        29.45833333  33.66666667  37.875
  42.08333333  46.29166667  50.5         54.70833333  58.91666667
  63.125       67.33333333  71.54166667  75.75        79.95833333
  84.16666667  88.375       92.58333333  96.79166667 101.        ]
[20 27 14 23 10]
[ 1.  0. -1. -1.  0.  1. -1. -1.  0.  1.]
[[33 20 27 48 24]
 [40 47 46 45 36]]
7
48
20
36.6
3
[[33 20 27 48 24]
 [40 47 46 45 36]]
[[40 47 46 45 36]
 [33 20 27 48 24]]
[33 20 27 48 24]
46
[33 40]
[[1089  400  729 2304  576]
 [1600 2209 2116 2025 1296]]
[[-36 -37  47 -48  24]
 [ 46  -3  14 -25 -50]]
[24 46 14]
