# Problem 1

In [16]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
x = np.random.randint(0,10,size=(2,5))
print(x)
# 3 - matris'in boyutunu öğrenin
print(x.ndim)
# 4 - matris'i yeniden boyutlandırın
x.reshape(5,2)
# 5 - matris'in boyut sayısını öğrenin
print(x.ndim)


[[5 3 2 0 3]
 [2 7 3 0 8]]
2
2


# Problem 2

In [61]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
a = np.random.choice(np.arange(1,10,2), size=(2,5))
print(a)

# 2 - Oluşturduğunuz matrisi parçalayın
a,b,c = np.split(a,[2,4], axis=1)
print(a)
print(b)        
print(c)
# 3 - Parçalanmış matrisleri birleştirin
combined = np.concatenate([a, b, c], axis=1)
print(combined)

[[1 9 5 9 7]
 [5 5 5 9 5]]
[[1 9]
 [5 5]]
[[5 9]
 [5 9]]
[[7]
 [5]]
[[1 9 5 9 7]
 [5 5 5 9 5]]


# Problem 3

In [ ]:
# 5 ile 100 arasında ikişer ikişer atlayarak 10 rastgele sayı seçelim
a = np.random.choice(np.arange(5, 101, 2), size=10)
print("Matris (a):")
print(a)

# 2 - matris'in özelliklerini inceleyin
print("Matrisin boyutu:", a.shape)
print("Matrisin boyut sayısı:", a.ndim)
print("Matrisin veri tipi:", a.dtype)
print("Matrisin toplam eleman sayısı:", a.size)
print("Matrisin toplamı:", a.sum())
print("Matrisin ortalaması:", a.mean())
print("Matrisin standart sapması:", a.std())
print("Matrisin maksimum değeri:", a.max())
print("Matrisin minimum değeri:", a.min())
print("Matrisin medyanı:", np.median(a))
print("Matrisin varyansı:", np.var(a))


Matris (a):
[75 19 69 89 79 43 55 59 79 45]
Matrisin boyutu: (10,)
Matrisin boyut sayısı: 1
Matrisin veri tipi: int64
Matrisin toplam eleman sayısı: 10
Matrisin toplamı: 612
Matrisin ortalaması: 61.2
Matrisin standart sapması: 20.188115315699978
Matrisin maksimum değeri: 89
Matrisin minimum değeri: 19
Matrisin medyanı: 64.0
Matrisin varyansı: 407.56
